name: auth-system-transformers
version: 0.1.0.0
description: "Система авторизации с монадными трансформерами"

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - text
  - mtl
  - transformers

library:
  source-dirs: src

executables:
  auth-system:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - auth-system-transformers